%%%%%%%%%%%%%%%%%%%%
% Step 5
% Label all patchs using the trained cluster_center generated by the last step
% Generate 'label' for every image
% Save 'label' into "../label"
%%%%%%%%%%%%%%%%%%%%

clear
close all
clc

% Load the cluster_center we trained
loaddata = load('../Clustercenter.mat');
cluster_center = loaddata.cluster_center;
number_cluster = size(cluster_center, 1);  

% Getting the count of files in "../LRFeature"
fileFolder = fullfile('../LRFeature');
dirOutput = dir(fullfile(fileFolder, '*.mat'));
fileNames = {dirOutput.name}';
[count, ~] = size(fileNames);

for cnt = 1:count
    filename = fileNames{cnt};
    fprintf('%d labeling %s \n', cnt, filename)
    loaddata = load(strcat('../LRFeature/', filename));
    feature = loaddata.feature;
    patch_number_for_this_image = size(feature, 1);
    % generate the label for this image
    label = zeros(patch_number_for_this_image, 1);
    for patch_query = 1:patch_number_for_this_image
        feature_query = feature(patch_query, :);
        diff = repmat(feature_query, [number_cluster, 1]) - cluster_center;
        dis2 = sqrt(sum(diff.^2,2));
        [~, label_this] = min(dis2);
        label(patch_query) = label_this;
    end
    save(strcat('../label/', filename), 'label');
end